<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="h0krq5kd.0hl~" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DSharpPlus" Version="4.4.9" />
    <PackageReference Include="DSharpPlus.CommandsNext" Version="4.4.9" />
    <PackageReference Include="DSharpPlus.Interactivity" Version="4.4.9" />
    <PackageReference Include="NLog" Version="5.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Config\Config.csproj" />
    <ProjectReference Include="..\Enums\Enums.csproj" />
    <ProjectReference Include="..\EventService\EventService.csproj" />
    <ProjectReference Include="..\Imbiss\Imbiss.csproj" />
    <ProjectReference Include="..\Services\Services.csproj" />
  </ItemGroup>

</Project>
